language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=Serializers
    - REQUIRE=""
    - PHPCS_ARGS="-p --extensions=php --standard=vendor/loadsys/loadsys_codesniffer/Loadsys --ignore=vendor/ ."

  matrix:
    - DB=mysql CAKE_VERSION=2.3
    - DB=mysql CAKE_VERSION=2.4
    - DB=mysql CAKE_VERSION=2.5
    - DB=mysql CAKE_VERSION=2.6

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
      - COVERALLS=1
      - DB=mysql
      - CAKE_VERSION=2.6
    - php: 5.6
      env:
      - DB=mysql
      - CAKE_VERSION=2.6
      - PHPCS=1
  allow_failures:
    - php: 5.6
      env:
      - DB=mysql
      - CAKE_VERSION=2.6
      - PHPCS=1

before_install:
  - composer self-update

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - composer require --dev --no-interaction --prefer-source loadsys/loadsys_codesniffer=*

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
