language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - CAKE_VERSION=2.1.5
  - CAKE_VERSION=2.2.9
  - CAKE_VERSION=2.3.10
  - CAKE_VERSION=2.4.10
  - CAKE_VERSION=2.5.6
  - CAKE_VERSION=master

install:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../CakePHP-Serializers plugins/Serializers
  - chmod -R 777 ../cakephp/app/tmp
  - sh -c "composer global require 'phpunit/phpunit=3.7.33'"
  - sh -c "ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ../cakephp/vendors/PHPUnit"

before_script:

script:
  - ./lib/Cake/Console/cake test Serializers AllSerializers --stderr

notifications:
  email: false
