sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=Serializers
    - REQUIRE=""
    - PHPCS_ARGS="-p --extensions=php --standard=vendor/loadsys/loadsys_codesniffer/Loadsys --ignore=vendor/ ."
    - secure: "gosy3etCdsMhQJnXD7zpfakja1FdRWjUY81G/7CNZte3hlC7JqRQM/mGRPWuP1MsWPySP5YiXVdiaYBJGXascCy19F6mXAuY/bmoRzigVpM0eDr5miokvXtev5UWqFgnJyg/CAwsat6uotOawxjKjwy1M4eyc0YFN4kQX7FDMds="

  matrix:
    - DB=mysql CAKE_VERSION=2.3
    - DB=mysql CAKE_VERSION=2.4
    - DB=mysql CAKE_VERSION=2.5
    - DB=mysql CAKE_VERSION=2.6

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
      - COVERALLS=1
      - DB=mysql
      - CAKE_VERSION=2.6
    - php: 5.6
      env:
      - DB=mysql
      - CAKE_VERSION=2.6
      - PHPCS=1
  allow_failures:
    - php: 5.6
      env:
      - DB=mysql
      - CAKE_VERSION=2.6
      - PHPCS=1

# Caching disabled for coveralls issues
# cache:
#   directories:
#     - vendor
#     - $HOME/.composer/cache

install:
  - composer config -g github-oauth.github.com $GITHUB_TOKEN
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - 'sed -i'''' ''s|curl |curl -H "Authorization: token \$GITHUB_TOKEN" |g'' ../travis/before_script.sh'

before_script:
  - ../travis/before_script.sh
  - composer require --no-interaction loadsys/loadsys_codesniffer:*
  - composer require --no-interaction loadsys/cakephp-serializers-errors:dev-master

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
